In [31]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('bmw_data.csv')
df

ileage  Age(yrs)  Sell Price($)
0    69000         6          18000
1    35000         3          34000
2    57000         5          26100
3    22500         2          40000
4    46000         4          31500
5    59000         5          26750
6    52000         5          32000
7    72000         6          19300
8    91000         8          12000
9    67000         6          22000
10   83000         7          18700
11   79000         7          19500
12   59000         5          26000
13   58780         4          27500
14   82450         7          19400
15   25400         3          35000
16   28000         2          35500
17   69000         5          19700
18   87600         8          12800
19   52000         5          28200

In [22]:
X=df.iloc[:,:-1].values
X

array([[69000,     6],
       [35000,     3],
       [57000,     5],
       [22500,     2],
       [46000,     4],
       [59000,     5],
       [52000,     5],
       [72000,     6],
       [91000,     8],
       [67000,     6],
       [83000,     7],
       [79000,     7],
       [59000,     5],
       [58780,     4],
       [82450,     7],
       [25400,     3],
       [28000,     2],
       [69000,     5],
       [87600,     8],
       [52000,     5]])

In [23]:
y=df.iloc[:,2].values
y

array([18000, 34000, 26100, 40000, 31500, 26750, 32000, 19300, 12000,
       22000, 18700, 19500, 26000, 27500, 19400, 35000, 35500, 19700,
       12800, 28200])

In [43]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X,y, test_size=.2, random_state=0)

In [44]:
X_train

array([[83000,     7],
       [69000,     5],
       [52000,     5],
       [58780,     4],
       [46000,     4],
       [57000,     5],
       [59000,     5],
       [82450,     7],
       [67000,     6],
       [72000,     6],
       [28000,     2],
       [79000,     7],
       [22500,     2],
       [69000,     6],
       [25400,     3],
       [59000,     5]])

In [45]:
reg=LinearRegression()
reg.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [46]:
reg.predict(X_test)

array([15968.88975121, 34057.45077682, 28308.037565  , 14718.28626739])

In [47]:
reg.score(X_test, y_test)

0.9524414164762771