In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

In [76]:
df = pd.read_csv('salary.csv')
X=df.iloc[:, :-1]
y=df.iloc[:,3]
df


experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         NaN                    8.0                           9      50000
1         NaN                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    NaN                           7      72000
7        11.0                    7.0                           8      80000

In [67]:
# Taking care of missing data
from sklearn.impute import SimpleImputer
imp = SimpleImputer(strategy="mean")
x = imp.fit_transform(X) 

In [60]:
type(x)

numpy.ndarray

In [62]:
x

array([[ 2.,  8.,  9.],
       [ 2.,  8.,  6.],
       [ 5.,  6.,  7.],
       [ 2., 10., 10.],
       [ 7.,  9.,  6.],
       [ 3.,  7., 10.],
       [10.,  7.,  7.],
       [11.,  7.,  8.]])

In [68]:
reg = linear_model.LinearRegression()
reg.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [69]:
reg.predict([[2,7,6]])

array([45330.97282759])

In [73]:
#Splitting Training data and Test data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 1/3, random_state = 0)

In [74]:
X_test

array([[10.        ,  7.85714286,  7.        ],
       [ 5.        ,  6.        ,  7.        ],
       [ 6.33333333,  8.        ,  6.        ]])

In [75]:
reg.predict(X_test)

array([70215.18793061, 54813.99505382, 57944.83157893])